# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/cb/cb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb || ORIG_REF_NAME==cb} -quiet] -quiet

# IP: bd/cb/ip/cb_vdp_native_slave_0_1/cb_vdp_native_slave_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_vdp_native_slave_0_1 || ORIG_REF_NAME==cb_vdp_native_slave_0_1} -quiet] -quiet

# IP: bd/cb/ip/cb_processing_system7_0_0/cb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_processing_system7_0_0 || ORIG_REF_NAME==cb_processing_system7_0_0} -quiet] -quiet

# IP: bd/cb/ip/cb_axi_gpio_0_0/cb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_axi_gpio_0_0 || ORIG_REF_NAME==cb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cb/ip/cb_clk_wiz_0_2/cb_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_clk_wiz_0_2 || ORIG_REF_NAME==cb_clk_wiz_0_2} -quiet] -quiet

# IP: bd/cb/ip/cb_axi_gpio_1_0/cb_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_axi_gpio_1_0 || ORIG_REF_NAME==cb_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cb/ip/cb_axi_gpio_2_0/cb_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_axi_gpio_2_0 || ORIG_REF_NAME==cb_axi_gpio_2_0} -quiet] -quiet

# IP: bd/cb/ip/cb_xbar_0/cb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_xbar_0 || ORIG_REF_NAME==cb_xbar_0} -quiet] -quiet

# IP: bd/cb/ip/cb_ps7_0_axi_periph_0/cb_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_ps7_0_axi_periph_0 || ORIG_REF_NAME==cb_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cb/ip/cb_rst_ps7_0_100M_0/cb_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_rst_ps7_0_100M_0 || ORIG_REF_NAME==cb_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cb/ip/cb_axi_gpio_3_0/cb_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_axi_gpio_3_0 || ORIG_REF_NAME==cb_axi_gpio_3_0} -quiet] -quiet

# IP: bd/cb/ip/cb_axi_gpio_4_0/cb_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_axi_gpio_4_0 || ORIG_REF_NAME==cb_axi_gpio_4_0} -quiet] -quiet

# IP: bd/cb/ip/cb_auto_pc_0/cb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb_auto_pc_0 || ORIG_REF_NAME==cb_auto_pc_0} -quiet] -quiet

# XDC: bd/cb/ip/cb_processing_system7_0_0/cb_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_processing_system7_0_0 || ORIG_REF_NAME==cb_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_0_0/cb_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_0_0 || ORIG_REF_NAME==cb_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_0_0/cb_axi_gpio_0_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_0_0/cb_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_0_0 || ORIG_REF_NAME==cb_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_clk_wiz_0_2/cb_clk_wiz_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_clk_wiz_0_2 || ORIG_REF_NAME==cb_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cb/ip/cb_clk_wiz_0_2/cb_clk_wiz_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_clk_wiz_0_2 || ORIG_REF_NAME==cb_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cb/ip/cb_clk_wiz_0_2/cb_clk_wiz_0_2_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_1_0/cb_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_1_0 || ORIG_REF_NAME==cb_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_1_0/cb_axi_gpio_1_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_1_0/cb_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_1_0 || ORIG_REF_NAME==cb_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_2_0/cb_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_2_0 || ORIG_REF_NAME==cb_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_2_0/cb_axi_gpio_2_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_2_0/cb_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_2_0 || ORIG_REF_NAME==cb_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_xbar_0/cb_xbar_0_ooc.xdc

# XDC: bd/cb/ip/cb_rst_ps7_0_100M_0/cb_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_rst_ps7_0_100M_0 || ORIG_REF_NAME==cb_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_rst_ps7_0_100M_0/cb_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_rst_ps7_0_100M_0 || ORIG_REF_NAME==cb_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_rst_ps7_0_100M_0/cb_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_3_0/cb_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_3_0 || ORIG_REF_NAME==cb_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_3_0/cb_axi_gpio_3_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_3_0/cb_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_3_0 || ORIG_REF_NAME==cb_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_4_0/cb_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_4_0 || ORIG_REF_NAME==cb_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_axi_gpio_4_0/cb_axi_gpio_4_0_ooc.xdc

# XDC: bd/cb/ip/cb_axi_gpio_4_0/cb_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cb_axi_gpio_4_0 || ORIG_REF_NAME==cb_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cb/ip/cb_auto_pc_0/cb_auto_pc_0_ooc.xdc

# XDC: bd/cb/cb_ooc.xdc
